-- ============================================================
-- CLEANUP: remove now-obsolete price fields from page_content.
-- These prices now live in pricing_items (see above) and are
-- managed from Admin -> Pricing instead of Admin -> Site Content.
-- Safe to run more than once (removing an already-removed key is a no-op).
-- ============================================================
update public.page_content set content = content - 'home_price_1_label' - 'home_price_1_amount' - 'home_price_1_desc' - 'home_price_2_label' - 'home_price_2_amount' - 'home_price_2_desc' - 'home_price_3_label' - 'home_price_3_amount' - 'home_price_3_desc' - 'home_price_4_label' - 'home_price_4_amount' - 'home_price_4_desc' where page_key = 'home';
update public.page_content set content = content - 'pricing_section_1_heading' - 'pricing_section_2_heading' - 'pricing_section_3_heading' - 'pricing_section_4_heading' - 'pricing_section_5_heading' - 'pricing_section_6_heading' - 'pricing_row_1_label' - 'pricing_row_1_amount' - 'pricing_row_2_label' - 'pricing_row_2_amount' - 'pricing_row_3_label' - 'pricing_row_3_amount' - 'pricing_row_4_label' - 'pricing_row_4_amount' - 'pricing_row_5_label' - 'pricing_row_5_amount' - 'pricing_row_6_label' - 'pricing_row_6_amount' - 'pricing_row_7_label' - 'pricing_row_7_amount' - 'pricing_row_8_label' - 'pricing_row_8_amount' - 'pricing_row_9_label' - 'pricing_row_9_amount' - 'pricing_row_10_label' - 'pricing_row_10_amount' - 'pricing_row_11_label' - 'pricing_row_11_amount' - 'pricing_row_12_label' - 'pricing_row_12_amount' - 'pricing_row_13_label' - 'pricing_row_13_amount' - 'pricing_row_14_label' - 'pricing_row_14_amount' - 'pricing_row_15_label' - 'pricing_row_15_amount' - 'pricing_row_16_label' - 'pricing_row_16_amount' - 'pricing_row_17_label' - 'pricing_row_17_amount' - 'pricing_row_18_label' - 'pricing_row_18_amount' - 'pricing_row_19_label' - 'pricing_row_19_amount' - 'pricing_row_1_desc' where page_key = 'pricing';
update public.page_content set content = content - 'svc_acrepair_pricing_heading' - 'svc_acrepair_price_1_label' - 'svc_acrepair_price_1_amount' - 'svc_acrepair_price_2_label' - 'svc_acrepair_price_2_amount' - 'svc_acrepair_price_3_label' - 'svc_acrepair_price_3_amount' where page_key = 'service_ac_repair';
update public.page_content set content = content - 'svc_acinstall_pricing_heading' - 'svc_acinstall_price_1_label' - 'svc_acinstall_price_1_amount' - 'svc_acinstall_price_2_label' - 'svc_acinstall_price_2_amount' - 'svc_acinstall_price_3_label' - 'svc_acinstall_price_3_amount' where page_key = 'service_ac_installation';
update public.page_content set content = content - 'svc_amc_plan_1_label' - 'svc_amc_plan_1_amount' - 'svc_amc_plan_2_label' - 'svc_amc_plan_2_amount' where page_key = 'service_amc';
update public.page_content set content = content - 'svc_fridge_pricing_heading' - 'svc_fridge_price_1_label' - 'svc_fridge_price_1_amount' - 'svc_fridge_price_2_label' - 'svc_fridge_price_2_amount' - 'svc_fridge_price_3_label' - 'svc_fridge_price_3_amount' where page_key = 'service_fridge_repair';
update public.page_content set content = content - 'svc_washer_pricing_heading' - 'svc_washer_price_1_label' - 'svc_washer_price_1_amount' - 'svc_washer_price_2_label' - 'svc_washer_price_2_amount' - 'svc_washer_price_3_label' - 'svc_washer_price_3_amount' where page_key = 'service_washing_machine';
